package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.CandidateHistory;
import vn.com.ecopharma.hrm.service.CandidateHistoryLocalServiceUtil;

/**
 * The extended model base implementation for the CandidateHistory service. Represents a row in the &quot;HRM_Recruitment_CandidateHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CandidateHistoryImpl}.
 * </p>
 *
 * @author tvt
 * @see CandidateHistoryImpl
 * @see vn.com.ecopharma.hrm.model.CandidateHistory
 * @generated
 */
public abstract class CandidateHistoryBaseImpl extends CandidateHistoryModelImpl
    implements CandidateHistory {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a candidate history model instance should use the {@link CandidateHistory} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CandidateHistoryLocalServiceUtil.addCandidateHistory(this);
        } else {
            CandidateHistoryLocalServiceUtil.updateCandidateHistory(this);
        }
    }
}
