package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.Candidate;
import vn.com.ecopharma.hrm.service.CandidateLocalServiceUtil;

/**
 * The extended model base implementation for the Candidate service. Represents a row in the &quot;HRM_Recruitment_Candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CandidateImpl}.
 * </p>
 *
 * @author tvt
 * @see CandidateImpl
 * @see vn.com.ecopharma.hrm.model.Candidate
 * @generated
 */
public abstract class CandidateBaseImpl extends CandidateModelImpl
    implements Candidate {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a candidate model instance should use the {@link Candidate} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CandidateLocalServiceUtil.addCandidate(this);
        } else {
            CandidateLocalServiceUtil.updateCandidate(this);
        }
    }
}
