package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.FileAttachment;
import vn.com.ecopharma.hrm.service.FileAttachmentLocalServiceUtil;

/**
 * The extended model base implementation for the FileAttachment service. Represents a row in the &quot;HRM_FileAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileAttachmentImpl}.
 * </p>
 *
 * @author tvt
 * @see FileAttachmentImpl
 * @see vn.com.ecopharma.hrm.model.FileAttachment
 * @generated
 */
public abstract class FileAttachmentBaseImpl extends FileAttachmentModelImpl
    implements FileAttachment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a file attachment model instance should use the {@link FileAttachment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FileAttachmentLocalServiceUtil.addFileAttachment(this);
        } else {
            FileAttachmentLocalServiceUtil.updateFileAttachment(this);
        }
    }
}
