package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.VacancyCandidate;
import vn.com.ecopharma.hrm.service.VacancyCandidateLocalServiceUtil;

/**
 * The extended model base implementation for the VacancyCandidate service. Represents a row in the &quot;HRM_Recruitment_VacancyCandidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VacancyCandidateImpl}.
 * </p>
 *
 * @author tvt
 * @see VacancyCandidateImpl
 * @see vn.com.ecopharma.hrm.model.VacancyCandidate
 * @generated
 */
public abstract class VacancyCandidateBaseImpl extends VacancyCandidateModelImpl
    implements VacancyCandidate {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a vacancy candidate model instance should use the {@link VacancyCandidate} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            VacancyCandidateLocalServiceUtil.addVacancyCandidate(this);
        } else {
            VacancyCandidateLocalServiceUtil.updateVacancyCandidate(this);
        }
    }
}
