package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.NoSuchModelException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.ContainerModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;
import com.liferay.portlet.trash.model.TrashEntry;
import com.liferay.portlet.trash.service.TrashEntryLocalServiceUtil;

import vn.com.ecopharma.hrm.model.Candidate;
import vn.com.ecopharma.hrm.model.CandidateModel;
import vn.com.ecopharma.hrm.model.CandidateSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Candidate service. Represents a row in the &quot;pf_Candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.hrm.model.CandidateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CandidateImpl}.
 * </p>
 *
 * @author tvt
 * @see CandidateImpl
 * @see vn.com.ecopharma.hrm.model.Candidate
 * @see vn.com.ecopharma.hrm.model.CandidateModel
 * @generated
 */
@JSON(strict = true)
public class CandidateModelImpl extends BaseModelImpl<Candidate>
    implements CandidateModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a candidate model instance should use the {@link vn.com.ecopharma.hrm.model.Candidate} interface instead.
     */
    public static final String TABLE_NAME = "pf_Candidate";
    public static final Object[][] TABLE_COLUMNS = {
            { "c_id", Types.BIGINT },
            { "first_name", Types.VARCHAR },
            { "middle_name", Types.VARCHAR },
            { "last_name", Types.VARCHAR },
            { "email", Types.VARCHAR },
            { "contact_number", Types.VARCHAR },
            { "comment_", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table pf_Candidate (c_id LONG not null primary key,first_name VARCHAR(75) null,middle_name VARCHAR(75) null,last_name VARCHAR(75) null,email VARCHAR(75) null,contact_number VARCHAR(75) null,comment_ VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table pf_Candidate";
    public static final String ORDER_BY_JPQL = " ORDER BY candidate.c_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY pf_Candidate.c_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.vn.com.ecopharma.hrm.model.Candidate"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.vn.com.ecopharma.hrm.model.Candidate"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.vn.com.ecopharma.hrm.model.Candidate"));
    private static ClassLoader _classLoader = Candidate.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Candidate.class
        };
    private long _c_id;
    private String _first_name;
    private String _middle_name;
    private String _last_name;
    private String _email;
    private String _contact_number;
    private String _comment;
    private Candidate _escapedModel;

    public CandidateModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Candidate toModel(CandidateSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Candidate model = new CandidateImpl();

        model.setC_id(soapModel.getC_id());
        model.setFirst_name(soapModel.getFirst_name());
        model.setMiddle_name(soapModel.getMiddle_name());
        model.setLast_name(soapModel.getLast_name());
        model.setEmail(soapModel.getEmail());
        model.setContact_number(soapModel.getContact_number());
        model.setComment(soapModel.getComment());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Candidate> toModels(CandidateSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Candidate> models = new ArrayList<Candidate>(soapModels.length);

        for (CandidateSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _c_id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setC_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _c_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Candidate.class;
    }

    @Override
    public String getModelClassName() {
        return Candidate.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("c_id", getC_id());
        attributes.put("first_name", getFirst_name());
        attributes.put("middle_name", getMiddle_name());
        attributes.put("last_name", getLast_name());
        attributes.put("email", getEmail());
        attributes.put("contact_number", getContact_number());
        attributes.put("comment", getComment());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long c_id = (Long) attributes.get("c_id");

        if (c_id != null) {
            setC_id(c_id);
        }

        String first_name = (String) attributes.get("first_name");

        if (first_name != null) {
            setFirst_name(first_name);
        }

        String middle_name = (String) attributes.get("middle_name");

        if (middle_name != null) {
            setMiddle_name(middle_name);
        }

        String last_name = (String) attributes.get("last_name");

        if (last_name != null) {
            setLast_name(last_name);
        }

        String email = (String) attributes.get("email");

        if (email != null) {
            setEmail(email);
        }

        String contact_number = (String) attributes.get("contact_number");

        if (contact_number != null) {
            setContact_number(contact_number);
        }

        String comment = (String) attributes.get("comment");

        if (comment != null) {
            setComment(comment);
        }
    }

    @JSON
    @Override
    public long getC_id() {
        return _c_id;
    }

    @Override
    public void setC_id(long c_id) {
        _c_id = c_id;
    }

    @JSON
    @Override
    public String getFirst_name() {
        if (_first_name == null) {
            return StringPool.BLANK;
        } else {
            return _first_name;
        }
    }

    @Override
    public void setFirst_name(String first_name) {
        _first_name = first_name;
    }

    @JSON
    @Override
    public String getMiddle_name() {
        if (_middle_name == null) {
            return StringPool.BLANK;
        } else {
            return _middle_name;
        }
    }

    @Override
    public void setMiddle_name(String middle_name) {
        _middle_name = middle_name;
    }

    @JSON
    @Override
    public String getLast_name() {
        if (_last_name == null) {
            return StringPool.BLANK;
        } else {
            return _last_name;
        }
    }

    @Override
    public void setLast_name(String last_name) {
        _last_name = last_name;
    }

    @JSON
    @Override
    public String getEmail() {
        if (_email == null) {
            return StringPool.BLANK;
        } else {
            return _email;
        }
    }

    @Override
    public void setEmail(String email) {
        _email = email;
    }

    @JSON
    @Override
    public String getContact_number() {
        if (_contact_number == null) {
            return StringPool.BLANK;
        } else {
            return _contact_number;
        }
    }

    @Override
    public void setContact_number(String contact_number) {
        _contact_number = contact_number;
    }

    @JSON
    @Override
    public String getComment() {
        if (_comment == null) {
            return StringPool.BLANK;
        } else {
            return _comment;
        }
    }

    @Override
    public void setComment(String comment) {
        _comment = comment;
    }

    @Override
    public int getStatus() {
        return 0;
    }

    @Override
    public TrashEntry getTrashEntry() throws PortalException, SystemException {
        if (!isInTrash()) {
            return null;
        }

        TrashEntry trashEntry = TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
                getTrashEntryClassPK());

        if (trashEntry != null) {
            return trashEntry;
        }

        TrashHandler trashHandler = getTrashHandler();

        if (!Validator.isNull(trashHandler.getContainerModelClassName())) {
            ContainerModel containerModel = null;

            try {
                containerModel = trashHandler.getParentContainerModel(this);
            } catch (NoSuchModelException nsme) {
                return null;
            }

            while (containerModel != null) {
                if (containerModel instanceof TrashedModel) {
                    TrashedModel trashedModel = (TrashedModel) containerModel;

                    return trashedModel.getTrashEntry();
                }

                trashHandler = TrashHandlerRegistryUtil.getTrashHandler(trashHandler.getContainerModelClassName());

                if (trashHandler == null) {
                    return null;
                }

                containerModel = trashHandler.getContainerModel(containerModel.getParentContainerModelId());
            }
        }

        return null;
    }

    @Override
    public long getTrashEntryClassPK() {
        return getPrimaryKey();
    }

    @Override
    public TrashHandler getTrashHandler() {
        return TrashHandlerRegistryUtil.getTrashHandler(getModelClassName());
    }

    @Override
    public boolean isInTrash() {
        if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isInTrashContainer() {
        TrashHandler trashHandler = getTrashHandler();

        if ((trashHandler == null) ||
                Validator.isNull(trashHandler.getContainerModelClassName())) {
            return false;
        }

        try {
            ContainerModel containerModel = trashHandler.getParentContainerModel(this);

            if (containerModel == null) {
                return false;
            }

            if (containerModel instanceof TrashedModel) {
                return ((TrashedModel) containerModel).isInTrash();
            }
        } catch (Exception e) {
        }

        return false;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Candidate.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Candidate toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Candidate) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        CandidateImpl candidateImpl = new CandidateImpl();

        candidateImpl.setC_id(getC_id());
        candidateImpl.setFirst_name(getFirst_name());
        candidateImpl.setMiddle_name(getMiddle_name());
        candidateImpl.setLast_name(getLast_name());
        candidateImpl.setEmail(getEmail());
        candidateImpl.setContact_number(getContact_number());
        candidateImpl.setComment(getComment());

        candidateImpl.resetOriginalValues();

        return candidateImpl;
    }

    @Override
    public int compareTo(Candidate candidate) {
        long primaryKey = candidate.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Candidate)) {
            return false;
        }

        Candidate candidate = (Candidate) obj;

        long primaryKey = candidate.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Candidate> toCacheModel() {
        CandidateCacheModel candidateCacheModel = new CandidateCacheModel();

        candidateCacheModel.c_id = getC_id();

        candidateCacheModel.first_name = getFirst_name();

        String first_name = candidateCacheModel.first_name;

        if ((first_name != null) && (first_name.length() == 0)) {
            candidateCacheModel.first_name = null;
        }

        candidateCacheModel.middle_name = getMiddle_name();

        String middle_name = candidateCacheModel.middle_name;

        if ((middle_name != null) && (middle_name.length() == 0)) {
            candidateCacheModel.middle_name = null;
        }

        candidateCacheModel.last_name = getLast_name();

        String last_name = candidateCacheModel.last_name;

        if ((last_name != null) && (last_name.length() == 0)) {
            candidateCacheModel.last_name = null;
        }

        candidateCacheModel.email = getEmail();

        String email = candidateCacheModel.email;

        if ((email != null) && (email.length() == 0)) {
            candidateCacheModel.email = null;
        }

        candidateCacheModel.contact_number = getContact_number();

        String contact_number = candidateCacheModel.contact_number;

        if ((contact_number != null) && (contact_number.length() == 0)) {
            candidateCacheModel.contact_number = null;
        }

        candidateCacheModel.comment = getComment();

        String comment = candidateCacheModel.comment;

        if ((comment != null) && (comment.length() == 0)) {
            candidateCacheModel.comment = null;
        }

        return candidateCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(15);

        sb.append("{c_id=");
        sb.append(getC_id());
        sb.append(", first_name=");
        sb.append(getFirst_name());
        sb.append(", middle_name=");
        sb.append(getMiddle_name());
        sb.append(", last_name=");
        sb.append(getLast_name());
        sb.append(", email=");
        sb.append(getEmail());
        sb.append(", contact_number=");
        sb.append(getContact_number());
        sb.append(", comment=");
        sb.append(getComment());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(25);

        sb.append("<model><model-name>");
        sb.append("vn.com.ecopharma.hrm.model.Candidate");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>c_id</column-name><column-value><![CDATA[");
        sb.append(getC_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>first_name</column-name><column-value><![CDATA[");
        sb.append(getFirst_name());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>middle_name</column-name><column-value><![CDATA[");
        sb.append(getMiddle_name());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>last_name</column-name><column-value><![CDATA[");
        sb.append(getLast_name());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>email</column-name><column-value><![CDATA[");
        sb.append(getEmail());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contact_number</column-name><column-value><![CDATA[");
        sb.append(getContact_number());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>comment</column-name><column-value><![CDATA[");
        sb.append(getComment());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
