package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.Employee_Titles;
import vn.com.ecopharma.hrm.service.Employee_TitlesLocalServiceUtil;

/**
 * The extended model base implementation for the Employee_Titles service. Represents a row in the &quot;pf_Employee_Titles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Employee_TitlesImpl}.
 * </p>
 *
 * @author tvt
 * @see Employee_TitlesImpl
 * @see vn.com.ecopharma.hrm.model.Employee_Titles
 * @generated
 */
public abstract class Employee_TitlesBaseImpl extends Employee_TitlesModelImpl
    implements Employee_Titles {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a employee_ titles model instance should use the {@link Employee_Titles} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Employee_TitlesLocalServiceUtil.addEmployee_Titles(this);
        } else {
            Employee_TitlesLocalServiceUtil.updateEmployee_Titles(this);
        }
    }
}
