package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.com.ecopharma.hrm.model.Employee_Titles_History;
import vn.com.ecopharma.hrm.model.Employee_Titles_HistoryModel;
import vn.com.ecopharma.hrm.model.Employee_Titles_HistorySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Employee_Titles_History service. Represents a row in the &quot;pf_Employee_Titles_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.com.ecopharma.hrm.model.Employee_Titles_HistoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Employee_Titles_HistoryImpl}.
 * </p>
 *
 * @author tvt
 * @see Employee_Titles_HistoryImpl
 * @see vn.com.ecopharma.hrm.model.Employee_Titles_History
 * @see vn.com.ecopharma.hrm.model.Employee_Titles_HistoryModel
 * @generated
 */
@JSON(strict = true)
public class Employee_Titles_HistoryModelImpl extends BaseModelImpl<Employee_Titles_History>
    implements Employee_Titles_HistoryModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a employee_ titles_ history model instance should use the {@link vn.com.ecopharma.hrm.model.Employee_Titles_History} interface instead.
     */
    public static final String TABLE_NAME = "pf_Employee_Titles_History";
    public static final Object[][] TABLE_COLUMNS = {
            { "employee_Titles_HistoryId", Types.BIGINT },
            { "employeeId", Types.BIGINT },
            { "titlesId", Types.BIGINT },
            { "set_date", Types.TIMESTAMP },
            { "note", Types.VARCHAR },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table pf_Employee_Titles_History (employee_Titles_HistoryId LONG not null primary key,employeeId LONG,titlesId LONG,set_date DATE null,note VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null)";
    public static final String TABLE_SQL_DROP = "drop table pf_Employee_Titles_History";
    public static final String ORDER_BY_JPQL = " ORDER BY employee_Titles_History.employee_Titles_HistoryId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY pf_Employee_Titles_History.employee_Titles_HistoryId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.vn.com.ecopharma.hrm.model.Employee_Titles_History"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.vn.com.ecopharma.hrm.model.Employee_Titles_History"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.vn.com.ecopharma.hrm.model.Employee_Titles_History"));
    private static ClassLoader _classLoader = Employee_Titles_History.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Employee_Titles_History.class
        };
    private long _employee_Titles_HistoryId;
    private long _employeeId;
    private long _titlesId;
    private Date _set_date;
    private String _note;
    private long _groupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private Date _createDate;
    private Date _modifiedDate;
    private Employee_Titles_History _escapedModel;

    public Employee_Titles_HistoryModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Employee_Titles_History toModel(
        Employee_Titles_HistorySoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Employee_Titles_History model = new Employee_Titles_HistoryImpl();

        model.setEmployee_Titles_HistoryId(soapModel.getEmployee_Titles_HistoryId());
        model.setEmployeeId(soapModel.getEmployeeId());
        model.setTitlesId(soapModel.getTitlesId());
        model.setSet_date(soapModel.getSet_date());
        model.setNote(soapModel.getNote());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Employee_Titles_History> toModels(
        Employee_Titles_HistorySoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Employee_Titles_History> models = new ArrayList<Employee_Titles_History>(soapModels.length);

        for (Employee_Titles_HistorySoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _employee_Titles_HistoryId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setEmployee_Titles_HistoryId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _employee_Titles_HistoryId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Employee_Titles_History.class;
    }

    @Override
    public String getModelClassName() {
        return Employee_Titles_History.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("employee_Titles_HistoryId",
            getEmployee_Titles_HistoryId());
        attributes.put("employeeId", getEmployeeId());
        attributes.put("titlesId", getTitlesId());
        attributes.put("set_date", getSet_date());
        attributes.put("note", getNote());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long employee_Titles_HistoryId = (Long) attributes.get(
                "employee_Titles_HistoryId");

        if (employee_Titles_HistoryId != null) {
            setEmployee_Titles_HistoryId(employee_Titles_HistoryId);
        }

        Long employeeId = (Long) attributes.get("employeeId");

        if (employeeId != null) {
            setEmployeeId(employeeId);
        }

        Long titlesId = (Long) attributes.get("titlesId");

        if (titlesId != null) {
            setTitlesId(titlesId);
        }

        Date set_date = (Date) attributes.get("set_date");

        if (set_date != null) {
            setSet_date(set_date);
        }

        String note = (String) attributes.get("note");

        if (note != null) {
            setNote(note);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }
    }

    @JSON
    @Override
    public long getEmployee_Titles_HistoryId() {
        return _employee_Titles_HistoryId;
    }

    @Override
    public void setEmployee_Titles_HistoryId(long employee_Titles_HistoryId) {
        _employee_Titles_HistoryId = employee_Titles_HistoryId;
    }

    @JSON
    @Override
    public long getEmployeeId() {
        return _employeeId;
    }

    @Override
    public void setEmployeeId(long employeeId) {
        _employeeId = employeeId;
    }

    @JSON
    @Override
    public long getTitlesId() {
        return _titlesId;
    }

    @Override
    public void setTitlesId(long titlesId) {
        _titlesId = titlesId;
    }

    @JSON
    @Override
    public Date getSet_date() {
        return _set_date;
    }

    @Override
    public void setSet_date(Date set_date) {
        _set_date = set_date;
    }

    @JSON
    @Override
    public String getNote() {
        if (_note == null) {
            return StringPool.BLANK;
        } else {
            return _note;
        }
    }

    @Override
    public void setNote(String note) {
        _note = note;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Employee_Titles_History.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Employee_Titles_History toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Employee_Titles_History) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        Employee_Titles_HistoryImpl employee_Titles_HistoryImpl = new Employee_Titles_HistoryImpl();

        employee_Titles_HistoryImpl.setEmployee_Titles_HistoryId(getEmployee_Titles_HistoryId());
        employee_Titles_HistoryImpl.setEmployeeId(getEmployeeId());
        employee_Titles_HistoryImpl.setTitlesId(getTitlesId());
        employee_Titles_HistoryImpl.setSet_date(getSet_date());
        employee_Titles_HistoryImpl.setNote(getNote());
        employee_Titles_HistoryImpl.setGroupId(getGroupId());
        employee_Titles_HistoryImpl.setCompanyId(getCompanyId());
        employee_Titles_HistoryImpl.setUserId(getUserId());
        employee_Titles_HistoryImpl.setCreateDate(getCreateDate());
        employee_Titles_HistoryImpl.setModifiedDate(getModifiedDate());

        employee_Titles_HistoryImpl.resetOriginalValues();

        return employee_Titles_HistoryImpl;
    }

    @Override
    public int compareTo(Employee_Titles_History employee_Titles_History) {
        long primaryKey = employee_Titles_History.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Employee_Titles_History)) {
            return false;
        }

        Employee_Titles_History employee_Titles_History = (Employee_Titles_History) obj;

        long primaryKey = employee_Titles_History.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Employee_Titles_History> toCacheModel() {
        Employee_Titles_HistoryCacheModel employee_Titles_HistoryCacheModel = new Employee_Titles_HistoryCacheModel();

        employee_Titles_HistoryCacheModel.employee_Titles_HistoryId = getEmployee_Titles_HistoryId();

        employee_Titles_HistoryCacheModel.employeeId = getEmployeeId();

        employee_Titles_HistoryCacheModel.titlesId = getTitlesId();

        Date set_date = getSet_date();

        if (set_date != null) {
            employee_Titles_HistoryCacheModel.set_date = set_date.getTime();
        } else {
            employee_Titles_HistoryCacheModel.set_date = Long.MIN_VALUE;
        }

        employee_Titles_HistoryCacheModel.note = getNote();

        String note = employee_Titles_HistoryCacheModel.note;

        if ((note != null) && (note.length() == 0)) {
            employee_Titles_HistoryCacheModel.note = null;
        }

        employee_Titles_HistoryCacheModel.groupId = getGroupId();

        employee_Titles_HistoryCacheModel.companyId = getCompanyId();

        employee_Titles_HistoryCacheModel.userId = getUserId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            employee_Titles_HistoryCacheModel.createDate = createDate.getTime();
        } else {
            employee_Titles_HistoryCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            employee_Titles_HistoryCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            employee_Titles_HistoryCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        return employee_Titles_HistoryCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{employee_Titles_HistoryId=");
        sb.append(getEmployee_Titles_HistoryId());
        sb.append(", employeeId=");
        sb.append(getEmployeeId());
        sb.append(", titlesId=");
        sb.append(getTitlesId());
        sb.append(", set_date=");
        sb.append(getSet_date());
        sb.append(", note=");
        sb.append(getNote());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("vn.com.ecopharma.hrm.model.Employee_Titles_History");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>employee_Titles_HistoryId</column-name><column-value><![CDATA[");
        sb.append(getEmployee_Titles_HistoryId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>employeeId</column-name><column-value><![CDATA[");
        sb.append(getEmployeeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>titlesId</column-name><column-value><![CDATA[");
        sb.append(getTitlesId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>set_date</column-name><column-value><![CDATA[");
        sb.append(getSet_date());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>note</column-name><column-value><![CDATA[");
        sb.append(getNote());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
