package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.Level;
import vn.com.ecopharma.hrm.service.LevelLocalServiceUtil;

/**
 * The extended model base implementation for the Level service. Represents a row in the &quot;pf_Level&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LevelImpl}.
 * </p>
 *
 * @author tvt
 * @see LevelImpl
 * @see vn.com.ecopharma.hrm.model.Level
 * @generated
 */
public abstract class LevelBaseImpl extends LevelModelImpl implements Level {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a level model instance should use the {@link Level} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LevelLocalServiceUtil.addLevel(this);
        } else {
            LevelLocalServiceUtil.updateLevel(this);
        }
    }
}
