package vn.com.ecopharma.hrm.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.com.ecopharma.hrm.model.Titles;
import vn.com.ecopharma.hrm.service.TitlesLocalServiceUtil;

/**
 * The extended model base implementation for the Titles service. Represents a row in the &quot;pf_Titles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TitlesImpl}.
 * </p>
 *
 * @author tvt
 * @see TitlesImpl
 * @see vn.com.ecopharma.hrm.model.Titles
 * @generated
 */
public abstract class TitlesBaseImpl extends TitlesModelImpl implements Titles {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a titles model instance should use the {@link Titles} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TitlesLocalServiceUtil.addTitles(this);
        } else {
            TitlesLocalServiceUtil.updateTitles(this);
        }
    }
}
