package vn.com.ecopharma.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;HRM_Recruitment_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author tvt
 * @see Employee
 * @see vn.com.ecopharma.hrm.model.impl.EmployeeImpl
 * @see vn.com.ecopharma.hrm.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee ID of this employee.
     *
     * @return the employee ID of this employee
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee.
     *
     * @param employeeId the employee ID of this employee
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the group ID of this employee.
     *
     * @return the group ID of this employee
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this employee.
     *
     * @param groupId the group ID of this employee
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this employee.
     *
     * @return the company ID of this employee
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this employee.
     *
     * @param companyId the company ID of this employee
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this employee.
     *
     * @return the user ID of this employee
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this employee.
     *
     * @param userId the user ID of this employee
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this employee.
     *
     * @return the user uuid of this employee
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this employee.
     *
     * @param userUuid the user uuid of this employee
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this employee.
     *
     * @return the user name of this employee
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this employee.
     *
     * @param userName the user name of this employee
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this employee.
     *
     * @return the create date of this employee
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this employee.
     *
     * @param createDate the create date of this employee
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this employee.
     *
     * @return the modified date of this employee
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this employee.
     *
     * @param modifiedDate the modified date of this employee
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the emp_code of this employee.
     *
     * @return the emp_code of this employee
     */
    @AutoEscape
    public String getEmp_code();

    /**
     * Sets the emp_code of this employee.
     *
     * @param emp_code the emp_code of this employee
     */
    public void setEmp_code(String emp_code);

    /**
     * Returns the firstname of this employee.
     *
     * @return the firstname of this employee
     */
    @AutoEscape
    public String getFirstname();

    /**
     * Sets the firstname of this employee.
     *
     * @param firstname the firstname of this employee
     */
    public void setFirstname(String firstname);

    /**
     * Returns the middle_name of this employee.
     *
     * @return the middle_name of this employee
     */
    @AutoEscape
    public String getMiddle_name();

    /**
     * Sets the middle_name of this employee.
     *
     * @param middle_name the middle_name of this employee
     */
    public void setMiddle_name(String middle_name);

    /**
     * Returns the lastname of this employee.
     *
     * @return the lastname of this employee
     */
    @AutoEscape
    public String getLastname();

    /**
     * Sets the lastname of this employee.
     *
     * @param lastname the lastname of this employee
     */
    public void setLastname(String lastname);

    /**
     * Returns the email of this employee.
     *
     * @return the email of this employee
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this employee.
     *
     * @param email the email of this employee
     */
    public void setEmail(String email);

    /**
     * Returns the contact_number of this employee.
     *
     * @return the contact_number of this employee
     */
    @AutoEscape
    public String getContact_number();

    /**
     * Sets the contact_number of this employee.
     *
     * @param contact_number the contact_number of this employee
     */
    public void setContact_number(String contact_number);

    /**
     * Returns the nickname of this employee.
     *
     * @return the nickname of this employee
     */
    @AutoEscape
    public String getNickname();

    /**
     * Sets the nickname of this employee.
     *
     * @param nickname the nickname of this employee
     */
    public void setNickname(String nickname);

    /**
     * Returns the birthday of this employee.
     *
     * @return the birthday of this employee
     */
    public Date getBirthday();

    /**
     * Sets the birthday of this employee.
     *
     * @param birthday the birthday of this employee
     */
    public void setBirthday(Date birthday);

    /**
     * Returns the gender of this employee.
     *
     * @return the gender of this employee
     */
    @AutoEscape
    public String getGender();

    /**
     * Sets the gender of this employee.
     *
     * @param gender the gender of this employee
     */
    public void setGender(String gender);

    /**
     * Returns the marital_status of this employee.
     *
     * @return the marital_status of this employee
     */
    @AutoEscape
    public String getMarital_status();

    /**
     * Sets the marital_status of this employee.
     *
     * @param marital_status the marital_status of this employee
     */
    public void setMarital_status(String marital_status);

    /**
     * Returns the status of this employee.
     *
     * @return the status of this employee
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this employee.
     *
     * @param status the status of this employee
     */
    public void setStatus(String status);

    /**
     * Returns the jobtitle ID of this employee.
     *
     * @return the jobtitle ID of this employee
     */
    public long getJobtitleId();

    /**
     * Sets the jobtitle ID of this employee.
     *
     * @param jobtitleId the jobtitle ID of this employee
     */
    public void setJobtitleId(long jobtitleId);

    /**
     * Returns the joined_date of this employee.
     *
     * @return the joined_date of this employee
     */
    public Date getJoined_date();

    /**
     * Sets the joined_date of this employee.
     *
     * @param joined_date the joined_date of this employee
     */
    public void setJoined_date(Date joined_date);

    /**
     * Returns the sub unit ID of this employee.
     *
     * @return the sub unit ID of this employee
     */
    public long getSubUnitId();

    /**
     * Sets the sub unit ID of this employee.
     *
     * @param subUnitId the sub unit ID of this employee
     */
    public void setSubUnitId(long subUnitId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Employee> toCacheModel();

    @Override
    public Employee toEscapedModel();

    @Override
    public Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
