package vn.com.ecopharma.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee_Titles_History service. Represents a row in the &quot;pf_Employee_Titles_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.com.ecopharma.hrm.model.impl.Employee_Titles_HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.com.ecopharma.hrm.model.impl.Employee_Titles_HistoryImpl}.
 * </p>
 *
 * @author tvt
 * @see Employee_Titles_History
 * @see vn.com.ecopharma.hrm.model.impl.Employee_Titles_HistoryImpl
 * @see vn.com.ecopharma.hrm.model.impl.Employee_Titles_HistoryModelImpl
 * @generated
 */
public interface Employee_Titles_HistoryModel extends BaseModel<Employee_Titles_History> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee_ titles_ history model instance should use the {@link Employee_Titles_History} interface instead.
     */

    /**
     * Returns the primary key of this employee_ titles_ history.
     *
     * @return the primary key of this employee_ titles_ history
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee_ titles_ history.
     *
     * @param primaryKey the primary key of this employee_ titles_ history
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee_ titles_ history ID of this employee_ titles_ history.
     *
     * @return the employee_ titles_ history ID of this employee_ titles_ history
     */
    public long getEmployee_Titles_HistoryId();

    /**
     * Sets the employee_ titles_ history ID of this employee_ titles_ history.
     *
     * @param employee_Titles_HistoryId the employee_ titles_ history ID of this employee_ titles_ history
     */
    public void setEmployee_Titles_HistoryId(long employee_Titles_HistoryId);

    /**
     * Returns the employee ID of this employee_ titles_ history.
     *
     * @return the employee ID of this employee_ titles_ history
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee_ titles_ history.
     *
     * @param employeeId the employee ID of this employee_ titles_ history
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the titles ID of this employee_ titles_ history.
     *
     * @return the titles ID of this employee_ titles_ history
     */
    public long getTitlesId();

    /**
     * Sets the titles ID of this employee_ titles_ history.
     *
     * @param titlesId the titles ID of this employee_ titles_ history
     */
    public void setTitlesId(long titlesId);

    /**
     * Returns the set_date of this employee_ titles_ history.
     *
     * @return the set_date of this employee_ titles_ history
     */
    public Date getSet_date();

    /**
     * Sets the set_date of this employee_ titles_ history.
     *
     * @param set_date the set_date of this employee_ titles_ history
     */
    public void setSet_date(Date set_date);

    /**
     * Returns the note of this employee_ titles_ history.
     *
     * @return the note of this employee_ titles_ history
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this employee_ titles_ history.
     *
     * @param note the note of this employee_ titles_ history
     */
    public void setNote(String note);

    /**
     * Returns the group ID of this employee_ titles_ history.
     *
     * @return the group ID of this employee_ titles_ history
     */
    public long getGroupId();

    /**
     * Sets the group ID of this employee_ titles_ history.
     *
     * @param groupId the group ID of this employee_ titles_ history
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this employee_ titles_ history.
     *
     * @return the company ID of this employee_ titles_ history
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this employee_ titles_ history.
     *
     * @param companyId the company ID of this employee_ titles_ history
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this employee_ titles_ history.
     *
     * @return the user ID of this employee_ titles_ history
     */
    public long getUserId();

    /**
     * Sets the user ID of this employee_ titles_ history.
     *
     * @param userId the user ID of this employee_ titles_ history
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this employee_ titles_ history.
     *
     * @return the user uuid of this employee_ titles_ history
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this employee_ titles_ history.
     *
     * @param userUuid the user uuid of this employee_ titles_ history
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this employee_ titles_ history.
     *
     * @return the create date of this employee_ titles_ history
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this employee_ titles_ history.
     *
     * @param createDate the create date of this employee_ titles_ history
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this employee_ titles_ history.
     *
     * @return the modified date of this employee_ titles_ history
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this employee_ titles_ history.
     *
     * @param modifiedDate the modified date of this employee_ titles_ history
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Employee_Titles_History employee_Titles_History);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Employee_Titles_History> toCacheModel();

    @Override
    public Employee_Titles_History toEscapedModel();

    @Override
    public Employee_Titles_History toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
